"""job visa sponsorship signal

Revision ID: 08e24994ab76
Revises: e9afcf22cd5b
Create Date: 2026-08-11 13:05:24.776416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e24994ab76'
down_revision: Union[str, Sequence[str], None] = 'e9afcf22cd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('visa_sponsorship', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('visa_sponsorship_evidence', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('visa_sponsorship_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'visa_sponsorship_checked_at')
    op.drop_column('jobs', 'visa_sponsorship_evidence')
    op.drop_column('jobs', 'visa_sponsorship')
    # ### end Alembic commands ###
