"""company research, contacts, outreach messages

Revision ID: deca3155b6cf
Revises: 4c744ac5c8da
Create Date: 2026-08-10 17:28:24.399202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deca3155b6cf'
down_revision: Union[str, Sequence[str], None] = '4c744ac5c8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_research',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('is_inference', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_research_company_id'), 'company_research', ['company_id'], unique=False)
    op.create_table('contacts',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('public_profile_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_company_id'), 'contacts', ['company_id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('personalization_rationale', sa.Text(), nullable=True),
    sa.Column('is_user_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_messages_candidate_id'), 'outreach_messages', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_job_id'), 'outreach_messages', ['job_id'], unique=False)
    op.create_foreign_key(None, 'applications', 'contacts', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'outreach_messages', ['outreach_message_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_index(op.f('ix_outreach_messages_job_id'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_candidate_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_contacts_company_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_research_company_id'), table_name='company_research')
    op.drop_table('company_research')
    # ### end Alembic commands ###
