"""company_research prompt_version

Revision ID: e9afcf22cd5b
Revises: deca3155b6cf
Create Date: 2026-08-11 12:11:59.232829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9afcf22cd5b'
down_revision: Union[str, Sequence[str], None] = 'deca3155b6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_research', sa.Column('prompt_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_research', 'prompt_version')
    # ### end Alembic commands ###
