"""JobBoardSource for the `new_grad_2027` profile: a public, community-maintained "New Grad
Positions" tracker repo's raw README, fetched via plain HTTPS GET (no auth, no API key).

The README is an HTML table (not a markdown pipe-table) embedded per role-category section,
regenerated by a bot with a consistent structure -- confirmed by inspecting the live file before
writing this parser. Each row: Company | Role | Location | Application (badge links) | Age.
Continuation rows (same company, another opening) use "↳" in the Company cell. Closed/inactive
listings lose their Application link entirely (replaced with a 🔒 emoji) -- rows with no
`<a href>` in that cell are skipped, since we only want postings still accepting applications.

Entirely deterministic (regex over a bot-generated, consistently-shaped document) -- no LLM
call, works under `LLM_PROVIDER=stub`.
"""

import html
import re
from collections.abc import Iterator
from datetime import date, timedelta

import httpx

from app.schemas.discovery import DiscoveredCompany, DiscoveredJob, DiscoveryQuery

_DEFAULT_RAW_URL = "https://raw.githubusercontent.com/SimplifyJobs/New-Grad-Positions/dev/README.md"
# Only these section headers are in scope -- matches the "broadened but not unlimited" role
# scope Adi confirmed for this profile (core SWE/data/AI roles plus quant/finance-adjacent
# ones), deliberately excluding e.g. Hardware Engineering / Product Management sections.
_DEFAULT_INCLUDED_SECTIONS = ("software engineering", "data science", "quantitative finance")

_SECTION_RE = re.compile(r"^## (.+)$", re.MULTILINE)
_TABLE_RE = re.compile(r"<table.*?</table>", re.DOTALL)
_ROW_RE = re.compile(r"<tr>(.*?)</tr>", re.DOTALL)
_CELL_RE = re.compile(r"<td.*?>(.*?)</td>", re.DOTALL)
_HREF_RE = re.compile(r'<a\s+href="([^"]+)"')
_TAG_RE = re.compile(r"<[^>]+>")
_AGE_RE = re.compile(r"^(\d+)(d|mo|y)$")
_CONTINUATION_MARKER = "↳"  # "↳"


def _strip_html(raw: str) -> str:
    return html.unescape(_TAG_RE.sub("", raw)).strip()


def _parse_age_to_date(age_text: str) -> date | None:
    match = _AGE_RE.match(age_text)
    if match is None:
        return None
    amount, unit = int(match.group(1)), match.group(2)
    days = amount if unit == "d" else amount * 30 if unit == "mo" else amount * 365
    return date.today() - timedelta(days=days)


class GitHubNewGradListSource:
    name = "github_new_grad_list"

    def __init__(
        self,
        client: httpx.Client | None = None,
        raw_url: str = _DEFAULT_RAW_URL,
        included_sections: tuple[str, ...] = _DEFAULT_INCLUDED_SECTIONS,
    ) -> None:
        self._client = client or httpx.Client(timeout=20.0)
        self._raw_url = raw_url
        self._included_sections = included_sections

    def search_jobs(self, query: DiscoveryQuery) -> list[DiscoveredJob]:
        response = self._client.get(self._raw_url)
        response.raise_for_status()
        jobs = list(self._parse_markdown(response.text))
        return [job for job in jobs if self._matches_query(job, query)]

    def _parse_markdown(self, markdown: str) -> Iterator[DiscoveredJob]:
        for header, body in self._iter_sections(markdown):
            if not any(keyword in header.lower() for keyword in self._included_sections):
                continue
            yield from self._parse_sections_tables(body)

    @staticmethod
    def _iter_sections(markdown: str) -> list[tuple[str, str]]:
        headers = list(_SECTION_RE.finditer(markdown))
        sections = []
        for i, match in enumerate(headers):
            start = match.end()
            end = headers[i + 1].start() if i + 1 < len(headers) else len(markdown)
            sections.append((_strip_html(match.group(1)), markdown[start:end]))
        return sections

    def _parse_sections_tables(self, body: str) -> Iterator[DiscoveredJob]:
        last_company: str | None = None
        for table_html in _TABLE_RE.findall(body):
            for row_html in _ROW_RE.findall(table_html):
                cells = _CELL_RE.findall(row_html)
                if len(cells) != 5:
                    continue
                company_html, role_html, location_html, application_html, age_html = cells

                href_match = _HREF_RE.search(application_html)
                if href_match is None:
                    continue  # closed/inactive -- no live application link

                company_text = _strip_html(company_html)
                is_continuation = company_text == _CONTINUATION_MARKER
                company_name = last_company if is_continuation else company_text
                if not company_name:
                    continue
                last_company = company_name

                job_url = href_match.group(1)
                posted_date = _parse_age_to_date(_strip_html(age_html))

                yield DiscoveredJob(
                    title=_strip_html(role_html),
                    job_url=job_url,
                    location=_strip_html(location_html) or None,
                    description=None,
                    work_mode=None,
                    posted_date=posted_date,
                    deadline_date=None,
                    company=DiscoveredCompany(
                        name=company_name,
                        source_url=self._raw_url,
                        source_type=self.name,
                    ),
                    source_url=job_url,
                    source_type=self.name,
                )

    @staticmethod
    def _matches_query(job: DiscoveredJob, query: DiscoveryQuery) -> bool:
        if not query.location_filters:
            return True
        haystack = f"{job.location or ''}".lower()
        return any(loc.lower() in haystack for loc in query.location_filters)
